### ISSUE TITLE
Customize export directory

### ISSUE THREAD

**Issue by VicPrzz00** [V-Sekai/Unidot-Importer#53]
Hi, I'm using this tool to move my assets, it's pretty great and stable but one issue I have is the export path. I'm exporting a big 9gb asset pack and the loading of the unitypackage alone takes x2 the space in [ unidot_extracted_tar ] and then there's the assets folder which is also currently 18gb, so this is 36gb in total. My main disc ran out of space during this process, and I couldn't set a different export location. Is there a way to do this? Is it also possible to maybe reduce the size of the whole process?

**Comment by lyuma** [comment]
The problem with .unitypackage is it is a compressed tar archive: there is no way to access the files inside without extracting it.

Unidot supports loading assets directly from an Assets folder, and then it should not need an additional extracted copy. To do this, browse to the Assets folder of the unity project and choose "select current folder" at the bottom of the file picker. My suggestion would be to do that and avoid using .unitypackage

i also will say 18GB is a lot to import at once. Even if it fits in disk at first, godot will do its own import and compression step which could also double the space afterwards

**Comment by VicPrzz00** [comment]
Hello, thanks for reaching out. Unfortunately, the asset bundle I'm trying to import comes only as a .unitypackage and it's 9GB. I tried importing it first into Unity but it went even worse.. As you can (hopefully) see in the screenshot, it went over 50GB when importing the package only for it to fail in the end (and take hours). Thanks for the information though, I'll note this for other smaller files
![wtf](https://github.com/V-Sekai/unidot_importer/assets/148383236/f8cea896-5773-401f-bce4-f59368056b20)
